name: CI - Build App Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t app-image ./app

      - name: Save Docker image as artifact
        run: docker save app-image -o app-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-image
          path: app-image.tar